### ISSUE TITLE
Provide a task for copying one file from source to destination

### ISSUE THREAD

**Issue by Nachtfeuer** [thomas-lehmann-private/hyperion#12]
Provide a task for copying one file from source to destination
```yaml
- type: file-copy
  ensure-path: true                                # optional
  overwrite: false                                 # optional
  source: c:\temp\source.txt
  destination: c:\temp\destination.txt
```

The defaults:
 * the destination path must exist (ensure-path set to false)
 * the overwrite mode is set to false.

However you can specify the boolean flag **ensure-path** that the path will be created.

The task will fail when:
* Permissions are not sufficient
* When the source file doesn't exist
* When the destination file already exists and the overwrite mode is set to false.
