### ISSUE TITLE
Provide a task for unpacking a zip file

### ISSUE THREAD

**Issue by Nachtfeuer** [thomas-lehmann-private/hyperion#14]
Provide a task for unpacking a zip file:

```yaml
- type: unzip
  ensure-path: false
  source: c:\temp\test.zip
  destination: c:\temp
```

Same as for copying a file the **ensure-path** is default false that
means the destination path must exist.

The task might fail when permissions are not sufficient
or the source doesn't exist.
